<?php

namespace IMIE\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConstructeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructeurRepository extends EntityRepository
{
}
