<?php

namespace IMIE\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielRepository extends EntityRepository
{

	public function FindByCat($cat)
	{
		  $qb = $this->createQueryBuilder('mat');

		  $qb->JOIN('mat.typeMateriel', 'type')
		    ->where('type.materiel =:cat')
		    ->setParameter('cat', $cat)
		  ;

		  return $qb
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function findbySalle($idSalle)
	{
		  $qb = $this->createQueryBuilder('mat');

		  $qb->JOIN('mat.salle', 'salle')
		    ->where('salle.id =:id')
		    ->setParameter('id', $idSalle)
		  ;

		  return $qb
		    ->getQuery()
		    ->getResult()
		  ;
	}

    public function findAll2()
    {
        return $this->findBy(array(), array('username' => 'ASC'));
    }

}
