<?php

namespace IMIE\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMaterielRepository extends EntityRepository
{

  public function getByCatQueryBuilder($cat)
  {
    return $this
      ->createQueryBuilder('a')
      ->where('a.materiel = :cat')
      ->setParameter('cat', $cat)
    ;
  }

}
