<?php

namespace IMIE\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeReseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeReseauRepository extends EntityRepository
{
}
